services:

  app:
    build: .
    container_name: codigo42-app

    ports:
      - "8080:80"

    volumes:
      - ./backend:/var/www/html

    env_file:
      - ./backend/.env

    command: >
      sh -c "
        echo '====================================' &&
        echo ' Código 42 - Iniciando Backend' &&
        echo '====================================' &&
        echo '' &&
        echo '[SWAGGER] Verificando documentação...' &&
        php /var/www/html/docs/gerar-swagger.php &&
        echo '[BACKEND] Iniciando Apache...' &&
        apache2-foreground
      "

    restart: unless-stopped


  frontend:
    build:
      context: ./web

    container_name: codigo42-frontend

    ports:
      - "8081:8080"

    volumes:
      - ./web:/app

    restart: unless-stopped