services:

  app:
    build: .
    container_name: codigo42-app

    ports:
      - "8080:80"

    volumes:
      - ./backend:/var/www/html

    env_file:
      - ./backend/.env

    restart: unless-stopped


  frontend:
    build:
      context: ./web

    container_name: codigo42-frontend

    ports:
      - "8081:8080"

    volumes:
      - ./web:/app

    restart: unless-stopped